name: Test nlpo3-js (JavaScript binding)
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "model/**"
      - "nlpo3-js/src/**"
      - "nlpo3-js/nlpo3/**"
      - "nlpo3-js/tests/**"
      - "nlpo3-js/Cargo.toml"
      - "nlpo3-js/package.json"
      - "nlpo3-js/package-lock.json"
      - "nlpo3-js/tsconfig.json"
      - ".github/workflows/test-nlpo3-js.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "model/**"
      - "nlpo3-js/src/**"
      - "nlpo3-js/nlpo3/**"
      - "nlpo3-js/tests/**"
      - "nlpo3-js/Cargo.toml"
      - "nlpo3-js/package.json"
      - "nlpo3-js/package-lock.json"
      - "nlpo3-js/tsconfig.json"
      - ".github/workflows/test-nlpo3-js.yml"

defaults:
  run:
    working-directory: nlpo3-js

jobs:
  test-js:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: ["22.x", "24.x", "current"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: nlpo3-js/package-lock.json

      - name: Install Node.js dependencies
        run: npm ci --ignore-scripts

      - name: Test publish
        run: npm pack --dry-run
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22.x'
        
      - name: Test
        run: npm test
